version: '2'
services:
  plex:
    image: plexinc/pms-docker:plexpass
    volumes:
      - plex_data:/config
      - /mnt/media:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
  nzbget:
    image: imdevinc/nzbget:latest
    ports:
      - "6789:6789"
    volumes:
      - /mnt/media/Downloads:/downloads
      - nzbget_data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
  medusa:
    image: imdevinc/medusa:latest
    ports:
      - "8081:8081"
    volumes:
      - medusa_data:/data
      - /mnt/media/Downloads:/downloads
      - /mnt/media/Anime:/anime
      - /mnt/media/TV Shows:/tv shows
      - /etc/localtime:/etc/localtime:ro
    restart: always
  couchpotato:
    image: imdevinc/couchpotato:latest
    ports:
      - "5050:5050"
    volumes:
      - cp_data:/data
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloads/CouchPotato:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
  ombi:
    image: lsiodev/ombi-preview
    ports:
      - "3579:3579"
    volumes:
      - ombi_data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
  tautulli:
    image: imdevinc/tautulli:latest
    ports:
      - "8181:8181"
    volumes:
      - tautulli_data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
  transmission:
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - transmission_data:/config
      - /mnt/media/Downloads/Torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
  mellow:
    image: voidp/mellow
    ports:
      - "5060:5060"
    volumes:
      - mellow_data:/usr/src/app/data
    restart: always
volumes:
  cp_data:
    driver: local
    name: plex-net_cp_data
  tautulli_data:
    driver: local
    name: plex-net_tautulli_data
  plex_data:
    driver: local
    name: plex-net_plex_data
  nzbget_data:
    driver: local
    name: plex-net_nzbget_data
  ombi_data:
    driver: local
    name: plex-net_ombi_data
  medusa_data:
    driver: local
    name: plex-net_medusa_data
  transmission_data:
    driver: local
    name: plex-net_transmission_data
  mellow_data:
    driver: local
    name: plex-net_mellow_data
