version: '2'
networks:
  plex-net:
services:
  plex:
    image: plexinc/pms-docker:plexpass
    ports:
      - "32400:32400"
    volumes:
      - plex_data:/config
      - /mnt/media:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  nzbget:
    image: imdevinc/nzbget
    ports:
      - "6789:6789"
    volumes:
      - /mnt/media/Downloads:/downloads
      - nzbget_data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  medusa:
    image: imdevinc/medusa
    ports:
      - "8081:8081"
    volumes:
      - medusa_data:/data
      - /mnt/media/Downloads:/downloads
      - /mnt/media/Anime:/anime
      - /mnt/media/TV Shows:/tv shows
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  couchpotato:
    image: imdevinc/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - cp_data:/data
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloads/CouchPotato:/downloads
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  ombi:
    image: lsiodev/ombi-preview
    ports:
      - "3579:3579"
    volumes:
      - ombi_data:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  tautulli:
    image: imdevinc/tautulli
    ports:
      - "8181:8181"
    volumes:
      - tautulli_data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  nginx:
    image: imdevinc/nginx-plex-net
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - plex-net
    restart: always
  transmission:
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
    volumes:
      - transmission_data:/config
      - /mnt/media/Downloads/Torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
  mellow:
    image: voidp/mellow
    ports:
      - "5060:5060"
    volumes:
      - mellow_data:/usr/src/app/data
    restart: always
volumes:
  cp_data:
  tautulli_data:
  plex_data:
  nzbget_data:
  ombi_data:
  medusa_data:
  transmission_data:
  mellow_data:
