version: '2'
services:
  portainer:
    image: 'portainer/portainer'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
volumes:
  portainer_data:
